Resources:
  DynamoDBTableLinks:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: ${self:provider.environment.SERVICE_DYNAMODB_TABLE_LINKS}
      BillingMode: PAY_PER_REQUEST #PROVISIONED

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

        - AttributeName: type
          AttributeType: S

        - AttributeName: shortLink
          AttributeType: S

        - AttributeName: createdAt
          AttributeType: N

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: typeCreatedAtGlobalIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH

            - AttributeName: createdAt
              KeyType: RANGE

          Projection:
            ProjectionType: ALL


        - IndexName: typeShortLinkGlobalIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH

            - AttributeName: shortLink
              KeyType: RANGE

          Projection:
            ProjectionType: ALL

