SERVICE_STAGE: ${self:provider.stage}

SERVICE_TEST_DYNAMODB_PORT: 9000

# DynamoDB
SERVICE_DYNAMODB_TABLE_THROUGHPUT_READ: 1
SERVICE_DYNAMODB_TABLE_THROUGHPUT_WRITE: 1

SERVICE_DYNAMODB_TABLE_LINKS: '${self:provider.stage}-Links'
